-- 1. إنشاء جدول العملاء (Customers)
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT PRIMARY KEY, -- الرقم الخاص بالزبون (يدخل يدوياً ومقترح تلقائياً من المنظومة)
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    debt NUMERIC NOT NULL DEFAULT 0.00,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. إنشاء جدول المعاملات والمنتجات المأخوذة (Transactions)
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
    amount NUMERIC NOT NULL, -- قيمة العملية (دائماً موجبة في التخزين)
    type TEXT NOT NULL,      -- نوع العملية: 'debt' (إضافة دين) أو 'pay' (تسديد دين)
    items TEXT,             -- المواد المأخوذة أو بيان التسديد
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. إنشاء جدول الإعدادات العامة للمنظومة (Settings)
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. دالة تلقائية (Trigger Function) لحساب الدين بشكل ديناميكي دقيق وآمن ومقاوم للأخطاء الحسابية عند أي تغيير
CREATE OR REPLACE FUNCTION public.handle_transaction_changes()
RETURNS TRIGGER AS $$
DECLARE
    target_customer_id BIGINT;
    calculated_debt NUMERIC;
BEGIN
    -- تحديد المعرف المستهدف بناءً على نوع العملية
    IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN
        target_customer_id := NEW.customer_id;
    ELSE
        target_customer_id := OLD.customer_id;
    END IF;

    -- إعادة حساب الدين بالكامل بشكل ديناميكي دقيق من واقع جدول المعاملات
    SELECT COALESCE(SUM(CASE WHEN type = 'debt' THEN amount ELSE -amount END), 0)
    INTO calculated_debt
    FROM public.transactions
    WHERE customer_id = target_customer_id;

    -- سقف الدين عند الصفر (لا يسمح بالقيم السالبة)
    calculated_debt := GREATEST(0, calculated_debt);

    -- تحديث حقل الدين الفعلي للعميل
    UPDATE public.customers
    SET debt = calculated_debt
    WHERE id = target_customer_id;

    -- في حالة تعديل حركة ونقلها لعميل آخر، نعيد الحساب للعميل القديم أيضاً
    IF TG_OP = 'UPDATE' AND OLD.customer_id <> NEW.customer_id THEN
        SELECT COALESCE(SUM(CASE WHEN type = 'debt' THEN amount ELSE -amount END), 0)
        INTO calculated_debt
        FROM public.transactions
        WHERE customer_id = OLD.customer_id;
        
        calculated_debt := GREATEST(0, calculated_debt);
        
        UPDATE public.customers
        SET debt = calculated_debt
        WHERE id = OLD.customer_id;
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. ربط الدالة بجدول المعاملات بواسطة Trigger عام لكافة العمليات
DROP TRIGGER IF EXISTS tr_on_transaction_change ON public.transactions;
CREATE TRIGGER tr_on_transaction_change
AFTER INSERT OR UPDATE OR DELETE ON public.transactions
FOR EACH ROW
EXECUTE FUNCTION public.handle_transaction_changes();

-- 6. إنشاء دوال الحماية والتحقق والعمليات الآمنة (RPC - Remote Procedure Calls)

-- أ. دالة التحقق الآمن من رمز مرور المشرف (PIN) على مستوى السيرفر دون إرساله للمتصفح
CREATE OR REPLACE FUNCTION public.check_admin_pin(input_pin TEXT)
RETURNS BOOLEAN AS $$
DECLARE
    db_pin TEXT;
BEGIN
    SELECT value INTO db_pin FROM public.settings WHERE key = 'admin_password';
    RETURN (db_pin = input_pin);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ب. دالة تسجيل حركة مالية آمنة ومحمية بالرمز السري
CREATE OR REPLACE FUNCTION public.add_transaction(
    pin TEXT,
    p_customer_id BIGINT,
    p_amount NUMERIC,
    p_type TEXT,
    p_items TEXT
) RETURNS BOOLEAN AS $$
BEGIN
    IF NOT public.check_admin_pin(pin) THEN
        RAISE EXCEPTION 'غير مصرح: رمز المرور (PIN) غير صحيح!';
    END IF;

    INSERT INTO public.transactions (customer_id, amount, type, items)
    VALUES (p_customer_id, p_amount, p_type, p_items);
    
    RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ج. دالة حذف حركة مالية آمنة ومحمية بالرمز السري
CREATE OR REPLACE FUNCTION public.delete_transaction(
    pin TEXT,
    p_id BIGINT
) RETURNS BOOLEAN AS $$
BEGIN
    IF NOT public.check_admin_pin(pin) THEN
        RAISE EXCEPTION 'غير مصرح: رمز المرور (PIN) غير صحيح!';
    END IF;

    DELETE FROM public.transactions WHERE id = p_id;
    RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- د. دالة تسجيل عميل جديد آمنة ومحمية بالرمز السري
CREATE OR REPLACE FUNCTION public.add_customer(
    pin TEXT,
    p_id BIGINT,
    p_name TEXT,
    p_phone TEXT
) RETURNS BOOLEAN AS $$
BEGIN
    IF NOT public.check_admin_pin(pin) THEN
        RAISE EXCEPTION 'غير مصرح: رمز المرور (PIN) غير صحيح!';
    END IF;

    INSERT INTO public.customers (id, name, phone, debt)
    VALUES (p_id, p_name, p_phone, 0);
    
    RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- هـ. دالة تعديل بيانات العميل آمنة ومحمية بالرمز السري
CREATE OR REPLACE FUNCTION public.update_customer(
    pin TEXT,
    p_id BIGINT,
    p_new_id BIGINT,
    p_new_name TEXT,
    p_new_phone TEXT
) RETURNS BOOLEAN AS $$
BEGIN
    IF NOT public.check_admin_pin(pin) THEN
        RAISE EXCEPTION 'غير مصرح: رمز المرور (PIN) غير صحيح!';
    END IF;

    -- التحقق من تكرار المعرف الجديد
    IF p_new_id <> p_id AND EXISTS (SELECT 1 FROM public.customers WHERE id = p_new_id) THEN
        RAISE EXCEPTION 'المعرف الجديد مستخدم بالفعل لعميل آخر!';
    END IF;

    UPDATE public.customers
    SET id = p_new_id, name = p_new_name, phone = p_new_phone
    WHERE id = p_id;
    
    RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- و. دالة حذف عميل بالكامل آمنة ومحمية بالرمز السري
CREATE OR REPLACE FUNCTION public.delete_customer(
    pin TEXT,
    p_id BIGINT
) RETURNS BOOLEAN AS $$
BEGIN
    IF NOT public.check_admin_pin(pin) THEN
        RAISE EXCEPTION 'غير مصرح: رمز المرور (PIN) غير صحيح!';
    END IF;

    DELETE FROM public.customers WHERE id = p_id;
    RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ز. دالة تحديث الإعدادات (مثل تحديث الرمز السري أو العملة) آمنة ومحمية بالرمز السري
CREATE OR REPLACE FUNCTION public.update_setting(
    pin TEXT,
    p_key TEXT,
    p_value TEXT
) RETURNS BOOLEAN AS $$
BEGIN
    -- في حالة تغيير رمز المرور، يجب مطابقة الرمز الحالي
    -- أما إذا لم تكن هناك كلمة مرور سابقة (أول إدخال)، يسمح بوضعها مباشرة
    IF EXISTS (SELECT 1 FROM public.settings WHERE key = 'admin_password') AND NOT public.check_admin_pin(pin) THEN
        RAISE EXCEPTION 'غير مصرح: رمز المرور الحالي (PIN) غير صحيح!';
    END IF;

    INSERT INTO public.settings (key, value)
    VALUES (p_key, p_value)
    ON CONFLICT (key) DO UPDATE SET value = p_value;
    
    RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 7. تفعيل الحماية والـ Row Level Security (RLS) على الجداول لمنع الاختراقات الخارجية
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

-- حذف أي سياسات سابقة لتفادي التعارض
DROP POLICY IF EXISTS "Allow public read-only non-sensitive settings" ON public.settings;
DROP POLICY IF EXISTS "Allow public read customers" ON public.customers;
DROP POLICY IF EXISTS "Allow public read transactions" ON public.transactions;

-- أ. سياسة جدول settings: السماح فقط بقراءة العملة وكود الدولة للعامة، وحظر قراءة الرمز السري تماماً
CREATE POLICY "Allow public read-only non-sensitive settings" 
ON public.settings FOR SELECT 
USING (key IN ('currency', 'country_code'));

-- ب. سياسة جدول العملاء: السماح للجميع بـ SELECT فقط (تتم التصفية والأمان في جانب العميل برمجياً وسيرفر)
CREATE POLICY "Allow public read customers" 
ON public.customers FOR SELECT 
USING (true);

-- ج. سياسة جدول المعاملات: السماح للجميع بـ SELECT فقط
CREATE POLICY "Allow public read transactions" 
ON public.transactions FOR SELECT 
USING (true);

-- 8. إضافة البيانات التجريبية الأولية والإعدادات الافتراضية
INSERT INTO public.settings (key, value) VALUES
('admin_password', '12345'),
('currency', 'ر.ي'),
('country_code', '967')
ON CONFLICT (key) DO NOTHING;

INSERT INTO public.customers (id, name, phone, debt) VALUES
(1001, 'أحمد محمد', '0912345678', 0),
(1002, 'خالد عبد الله', '0922345678', 0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.transactions (customer_id, amount, type, items, created_at) VALUES
(1001, 50.00, 'debt', 'زيت طهي، كيلو سكر', NOW() - INTERVAL '1 day'),
(1001, 70.00, 'debt', 'علبة حليب، كيس دقيق', NOW()),
(1002, 30.00, 'debt', 'علبة تونة، صابون', NOW() - INTERVAL '2 days'),
(1002, 30.00, 'pay', 'تسديد نقدي كامل للديون', NOW() - INTERVAL '1 day')
ON CONFLICT DO NOTHING;
