-- 1. إنشاء جدول العملاء (Customers)
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT PRIMARY KEY, -- الرقم الخاص بالزبون (يدخل يدوياً ومقترح تلقائياً من المنظومة)
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    debt NUMERIC NOT NULL DEFAULT 0.00,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. إنشاء جدول المعاملات والمنتجات المأخوذة (Transactions)
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
    amount NUMERIC NOT NULL, -- قيمة العملية (دائماً موجبة في التخزين)
    type TEXT NOT NULL,      -- نوع العملية: 'debt' (إضافة دين) أو 'pay' (تسديد دين)
    items TEXT,             -- المواد المأخوذة أو بيان التسديد
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. إنشاء جدول الإعدادات العامة للمنظومة (Settings)
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. إنشاء دالة تلقائية (Trigger Function) لتحديث دين العميل عند أي تغيير (إضافة / تعديل / حذف)
CREATE OR REPLACE FUNCTION public.handle_transaction_changes()
RETURNS TRIGGER AS $$
BEGIN
    -- في حالة إضافة حركة جديدة
    IF TG_OP = 'INSERT' THEN
        IF NEW.type = 'debt' THEN
            UPDATE public.customers
            SET debt = debt + NEW.amount
            WHERE id = NEW.customer_id;
        ELSIF NEW.type = 'pay' THEN
            UPDATE public.customers
            SET debt = GREATEST(0, debt - NEW.amount)
            WHERE id = NEW.customer_id;
        END IF;
        
    -- في حالة حذف حركة سابقة (عكس التأثير لسلامة الدفتر)
    ELSIF TG_OP = 'DELETE' THEN
        IF OLD.type = 'debt' THEN
            UPDATE public.customers
            SET debt = GREATEST(0, debt - OLD.amount)
            WHERE id = OLD.customer_id;
        ELSIF OLD.type = 'pay' THEN
            UPDATE public.customers
            SET debt = debt + OLD.amount
            WHERE id = OLD.customer_id;
        END IF;
        
    -- في حالة تعديل حركة سابقة
    ELSIF TG_OP = 'UPDATE' THEN
        -- أولاً: التراجع عن القيمة القديمة
        IF OLD.type = 'debt' THEN
            UPDATE public.customers
            SET debt = GREATEST(0, debt - OLD.amount)
            WHERE id = OLD.customer_id;
        ELSIF OLD.type = 'pay' THEN
            UPDATE public.customers
            SET debt = debt + OLD.amount
            WHERE id = OLD.customer_id;
        END IF;
        -- ثانياً: تطبيق القيمة الجديدة
        IF NEW.type = 'debt' THEN
            UPDATE public.customers
            SET debt = debt + NEW.amount
            WHERE id = NEW.customer_id;
        ELSIF NEW.type = 'pay' THEN
            UPDATE public.customers
            SET debt = GREATEST(0, debt - NEW.amount)
            WHERE id = NEW.customer_id;
        END IF;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- 5. ربط الدالة بجدول المعاملات بواسطة Trigger عام لكافة العمليات
DROP TRIGGER IF EXISTS tr_on_transaction_insert ON public.transactions;
DROP TRIGGER IF EXISTS tr_on_transaction_change ON public.transactions;

CREATE TRIGGER tr_on_transaction_change
AFTER INSERT OR UPDATE OR DELETE ON public.transactions
FOR EACH ROW
EXECUTE FUNCTION public.handle_transaction_changes();

-- 6. إضافة البيانات التجريبية الأولية والإعدادات الافتراضية
INSERT INTO public.settings (key, value) VALUES
('admin_password', '12345')
ON CONFLICT (key) DO NOTHING;

INSERT INTO public.customers (id, name, phone, debt) VALUES
(1001, 'أحمد محمد', '0912345678', 0),
(1002, 'خالد عبد الله', '0922345678', 0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.transactions (customer_id, amount, type, items, created_at) VALUES
(1001, 50.00, 'debt', 'زيت طهي، كيلو سكر', NOW() - INTERVAL '1 day'),
(1001, 70.00, 'debt', 'علبة حليب، كيس دقيق', NOW()),
(1002, 30.00, 'debt', 'علبة تونة، صابون', NOW() - INTERVAL '2 days'),
(1002, 30.00, 'pay', 'تسديد نقدي كامل للديون', NOW() - INTERVAL '1 day')
ON CONFLICT DO NOTHING;
